### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [HimanshuHP/KedditByPH#1]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by himanshuPH** [comment]
I can try this for newer projects and will get back to you if got any issues while integrating. Morever, i think you should write blog on medium or somewhere else so that more people get to know about this.

**Comment by oleksiyp** [comment]
I have some:

https://dzone.com/articles/new-mocking-tool-for-kotlin-an-alternative-to-java
https://habrahabr.ru/post/341202/ (RU)

and going to do more.

**Comment by himanshuPH** [comment]
You can mention blog link on github  as well.
